#!/usr/local/bin/bash

# usage : bash quick_certificate.sh smile.sa
mkdir hostRelated
cp ca.crt ./hostRelated/ca.crt
cp ca.key ./hostRelated/ca.key
cd hostRelated

echo "default_bits = 2048" > rkhuncle.conf
echo "prompt = no" >> rkhuncle.conf
echo "default_md = sha256" >> rkhuncle.conf
echo "distinguished_name = req_distinguished_name" >> rkhuncle.conf
echo "req_extensions = req_ext" >> rkhuncle.conf

echo "[req_distinguished_name]" >> rkhuncle.conf
echo "C  = TW" >> rkhuncle.conf
echo "ST = TW" >> rkhuncle.conf
echo "L  = Tainan" >>rkhuncle.conf
echo "O  = NCKU" >> rkhuncle.conf
echo "CN = $1" >> rkhuncle.conf

echo "[req_ext]" >> rkhuncle.conf
echo "subjectAltName = @alt_names " >> rkhuncle.conf

echo "[alt_names]" >> rkhuncle.conf
echo "DNS.1 = $1" >> rkhuncle.conf

cat rkhuncle.conf

chmod 777 rkhuncle.conf

openssl genrsa -out rkhuncle.key 2048
chmod 644 rkhuncle.key
openssl req -new -sha256 -key rkhuncle.key -out rkhuncle.csr -config rkhuncle.conf
chmod 777 rkhuncle.csr
openssl x509 -req -in rkhuncle.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out rkhuncle.crt -days 365 -sha256 -extensions req_ext -extfile rkhuncle.conf
chmod 777 rkhuncle.crt

cat rkhuncle.crt ca.crt > chained.crt
cp chained.crt ../rkhuncle.crt
cp rkhuncle.key ../rkhuncle.key